### Update and existing patient entity

PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "John Doe",
  "email": "johnDoe1@gmail.com",
  "address": "123 main Street",
  "dateOfBirth": "1992-09-09",
  "registeredDate": "2025-10-27"
}

###